### ISSUE TITLE
Cleanup Tasks

### ISSUE THREAD

**Issue by brian-ruf-ezd** [EasyDynamics/oscal-rest#82]
This Epic captures all of the tasks that must be performed before finalizing the draft specification.

```[tasklist]
### Tasks
- [ ] https://github.com/EasyDynamics/oscal-rest/issues/76
- [ ] #78
- [ ] https://github.com/EasyDynamics/oscal-rest/issues/77
- [ ] https://github.com/EasyDynamics/oscal-rest/issues/79
- [ ] https://github.com/EasyDynamics/oscal-rest/issues/80
- [ ] #81
- [ ] https://github.com/EasyDynamics/oscal-rest/issues/83
- [ ] https://github.com/EasyDynamics/oscal-rest/issues/84
- [ ] https://github.com/EasyDynamics/oscal-rest/issues/85
- [ ] https://github.com/EasyDynamics/oscal-rest/issues/87
- [ ] https://github.com/EasyDynamics/oscal-rest/issues/88
- [ ] https://github.com/EasyDynamics/oscal-rest/issues/89
- [ ] https://github.com/EasyDynamics/oscal-rest/issues/90
- [ ] https://github.com/EasyDynamics/oscal-rest/issues/91
```

**Comment by brian-ruf-ezd** [comment]
All tasks complete.
