### ISSUE TITLE
Replace PATCH With Specific Limited PUT Endpoints

### ISSUE THREAD

**Issue by brian-ruf-ezd** [EasyDynamics/oscal-rest#87]
### Description

To simplify the implementation effort required for the OSCAL REST OpenAPI specification, we should eliminate the `PATCH` method and instead introduce a limited set of PUT endpoints. 

Under the current Concept of Operations (ConOps), there are only a few reasons for modifying the content within the OSCAL content when sharing, managing attachments or producing snapshots. 

The use cases for this include:
- Managing attachment metadata (`back-matter/resource` content) (Covered as part of Issue #83)
- Managing limited snapshot metadata (select `metadata` props and links) (Addressed in Issue #85 and #86)

### Acceptance Criteria

- [x] The `PATCH` method is removed from the OSCAL REST OpenAPI syntax
- [ ] Issues in the Task List below are resolved
- [x] Remove patch heading and paragraphs from `info/description` as described below.

### Updated Info Description

The revised info/description should simply include the following. (Replace all current content with the following):
```
    A draft proposal from [Easy Dynamics](https://www.easydynamics.com) of a REST API specification for exchanging 
    [OSCAL](https://pages.nist.gov/OSCAL/) content between tool instances and organizations.  

    Standardized data models like OSCAL lay the groundwork for interoperability of systems, and an ecosystem of
    meaningful integrations can be brought to life through a standardized REST API.  Such an API will likely see the most 
    success across various vendors and projects when maintained by a standards body or community, and we're looking 
    to get that conversation started with this effort.

    For an overview and more information, visit [https://docs.oscal.io/docs/oscal-rest-openapi](https://docs.oscal.io/docs/oscal-rest-openapi)
 
```

```[tasklist]
### Tasks
- [ ] #83
- [ ] https://github.com/EasyDynamics/oscal-rest/issues/84
- [ ] #85
```

**Comment by brian-ruf-ezd** [comment]
Everything actionable in this issue is addressed in PR #72. The three linked issues are still pending work or review, but as they are being tracked separately I am good closing issue.
